plugins {
    id 'com.gradleup.shadow' version '8.3.6' apply false
}

allprojects {
    group = 'ru.leymooo'
    version = '1.0.1-RELEASE'
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}

project(':antirelog-modern') {
    plugins.withId('java') {
        dependencies {
            compileOnly('com.github.7byloper.suncore-recode:core:1.0.8-RELEASE')
        }
    }
}

tasks.register('legacyJar') {
    group = 'build'
    dependsOn ':antirelog-legacy:shadowJar'
}

tasks.register('modernJar') {
    group = 'build'
    dependsOn ':antirelog-modern:shadowJar'
}

tasks.register('buildPlugins') {
    group = 'build'
    dependsOn legacyJar
    dependsOn modernJar
}
