# Настройки кулдаунов для предметов
item-cooldowns:
  golden-apple:
    material: [ GOLDEN_APPLE ]
    cooldown: 15
    action_cooldown: [ EAT ]

  ench-golden-apple:
    material: [ ENCHANTED_GOLDEN_APPLE ]
    cooldown: 20
    action_cooldown: [ EAT ]

  chorus:
    material: [ CHORUS_FRUIT ]
    cooldown: 30
    action_cooldown: [ EAT ]

  ender-pearl:
    material: [ ENDER_PEARL ]
    cooldown: 15
    action_cooldown: [ USE ]

  fireworks:
    material: [ FIREWORK_ROCKET ]
    cooldown: 5
    action_cooldown: [ USE ]

  wind-charge:
    material: [ WIND_CHARGE ]
    cooldown: 10
    action_cooldown: [ USE ]

  mace:
    material: [ MACE ]
    cooldown: 5
    action_cooldown: [ ATTACK ]

  bow:
    material: [ BOW ]
    cooldown: 5
    action_cooldown: [ USE ]

  crossbow:
    material: [ CROSSBOW ]
    cooldown: 5
    action_cooldown: [ USE ]

  spears:
    material: [ SPEAR ]
    cooldown: 5
    action_cooldown: [ ATTACK, USE ]

# Настройки кулдаунов для зелий
potions-cooldowns: {}

# Длительность PVP режима (в секундах)
pvp-time: 30

# Блокировка команд во время PVP
disable-commands-in-pvp: true

# Разрешенные команды во время PVP (без '/')
commands-whitelist:
  - spec

# Блокировка открытия эндер-сундука во время PVP
disable-ender-chest-in-pvp: true

# Блокировка телепортаций во время PVP
disable-teleports-in-pvp: true

# Отменять ли взаимодействие с энтити во время PVP
cancel-interact-with-entities: false

# Убивать ли игрока при выходе во время PVP
kill-on-leave: true

# Убивать ли игрока при кике во время PVP
kill-on-kick: true

# Выполнять ли команды при кике во время PVP
run-commands-on-kick: true

# Фильтр сообщений кика для применения наказания (пусто - для любых причин кика)
kick-messages: []

# Команды от имени консоли при выходе игрока во время PVP
commands-on-leave: []

# Отключать ли полет, креатив и бессмертие у игрока при входе в PVP
disable-powerups: true

# Команды при отключении усилений
commands-on-powerups-disable: []

# Игнорировать ли запрет PVP в WorldGuard во время боя
ignore-worldguard: true

# Вступать ли в PVP при нанесении урона в зоне WorldGuard с pvp deny
join-pvp-in-worldguard: false

# Список игнорируемых регионов WorldGuard
ignored-worldguard-regions: []

# Отключать ли активный PVP режим при входе в игнорируемый регион
disable-pvp-in-ignored-region: true

# Список миров, в которых плагин отключен
disabled-worlds: []

# Включить ли отображение скорборда во время PVP (требуется плагин TAB)
enable-scoreboard: true

# Отображение оставшегося кулдауна предмета в actionbar при удержании в руке
item-cooldown-actionbar:
  enabled: false
  update-ticks: 5
