name: AntiRelog
main: ru.leymooo.antirelog.AntiRelog

version: '${version}'
api-version: '1.16'

website: t.me/bySunDev

depend: [ SunCore ]
softdepend:
  - PlaceholderAPI
  - Essentials
  - WorldGuard
  - CMI
  - TAB

authors: [ Leymooo, Loper ]
